[[inputs.exec]]
  commands = [["/usr/bin/python3", "/usr/local/bin/2md-logs-export.py"]]
  timeout = "15s"
  interval = "1m"
  data_format = "influx"

  [inputs.exec.tags]
    service = "888-url2md"
    instance = "2md.aiurl.tw"
